# makefile for the hpc course
CC      = gcc
OPT     = -g -O3
WARN    = -Wall
CFLAGS  = $(OPT) $(WARN) # the compiler flags
OBJECTS = data.o main.o io.o


# define project
excer2 : $(OBJECTS)
	$(CC) $(CFLAGS) -o excer2 $(OBJECTS)

clean : 
	@rm -f *.o compiler

realclean : clean
	@rm -f excer2

# define file dependencies
# DO NOT DELETE

data.o: /usr/include/stdio.h /usr/include/sys/cdefs.h
data.o: /usr/include/sys/_symbol_aliasing.h
data.o: /usr/include/sys/_posix_availability.h /usr/include/Availability.h
data.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
data.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
data.o: /usr/include/i386/_types.h /usr/include/sys/_pthread/_pthread_types.h
data.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/_types/_size_t.h
data.o: /usr/include/sys/_types/_null.h /usr/include/sys/stdio.h
data.o: /usr/include/sys/_types/_off_t.h /usr/include/sys/_types/_ssize_t.h
data.o: /usr/include/secure/_stdio.h /usr/include/secure/_common.h data.h
io.o: /usr/include/stdio.h /usr/include/sys/cdefs.h
io.o: /usr/include/sys/_symbol_aliasing.h
io.o: /usr/include/sys/_posix_availability.h /usr/include/Availability.h
io.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
io.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
io.o: /usr/include/i386/_types.h /usr/include/sys/_pthread/_pthread_types.h
io.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/_types/_size_t.h
io.o: /usr/include/sys/_types/_null.h /usr/include/sys/stdio.h
io.o: /usr/include/sys/_types/_off_t.h /usr/include/sys/_types/_ssize_t.h
io.o: /usr/include/secure/_stdio.h /usr/include/secure/_common.h io.h
main.o: /usr/include/stdio.h /usr/include/sys/cdefs.h
main.o: /usr/include/sys/_symbol_aliasing.h
main.o: /usr/include/sys/_posix_availability.h /usr/include/Availability.h
main.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
main.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
main.o: /usr/include/i386/_types.h /usr/include/sys/_pthread/_pthread_types.h
main.o: /usr/include/sys/_types/_va_list.h /usr/include/sys/_types/_size_t.h
main.o: /usr/include/sys/_types/_null.h /usr/include/sys/stdio.h
main.o: /usr/include/sys/_types/_off_t.h /usr/include/sys/_types/_ssize_t.h
main.o: /usr/include/secure/_stdio.h /usr/include/secure/_common.h
main.o: /usr/include/stdlib.h /usr/include/sys/wait.h
main.o: /usr/include/sys/_types/_pid_t.h /usr/include/sys/_types/_id_t.h
main.o: /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h
main.o: /usr/include/machine/signal.h /usr/include/i386/signal.h
main.o: /usr/include/machine/_mcontext.h /usr/include/i386/_mcontext.h
main.o: /usr/include/mach/i386/_structs.h
main.o: /usr/include/sys/_pthread/_pthread_attr_t.h
main.o: /usr/include/sys/_types/_sigaltstack.h
main.o: /usr/include/sys/_types/_ucontext.h
main.o: /usr/include/sys/_types/_sigset_t.h /usr/include/sys/_types/_uid_t.h
main.o: /usr/include/sys/resource.h /usr/include/stdint.h
main.o: /usr/include/sys/_types/_int8_t.h /usr/include/sys/_types/_int16_t.h
main.o: /usr/include/sys/_types/_int32_t.h /usr/include/sys/_types/_int64_t.h
main.o: /usr/include/_types/_uint8_t.h /usr/include/_types/_uint16_t.h
main.o: /usr/include/_types/_uint32_t.h /usr/include/_types/_uint64_t.h
main.o: /usr/include/sys/_types/_intptr_t.h
main.o: /usr/include/sys/_types/_uintptr_t.h /usr/include/_types/_intmax_t.h
main.o: /usr/include/_types/_uintmax_t.h /usr/include/sys/_types/_timeval.h
main.o: /usr/include/machine/endian.h /usr/include/i386/endian.h
main.o: /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h
main.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
main.o: /usr/include/sys/_types/_ct_rune_t.h
main.o: /usr/include/sys/_types/_rune_t.h /usr/include/sys/_types/_wchar_t.h
main.o: /usr/include/machine/types.h /usr/include/i386/types.h
main.o: /usr/include/sys/_types/_u_int8_t.h
main.o: /usr/include/sys/_types/_u_int16_t.h
main.o: /usr/include/sys/_types/_u_int32_t.h
main.o: /usr/include/sys/_types/_u_int64_t.h /usr/include/sys/_types/_dev_t.h
main.o: /usr/include/sys/_types/_mode_t.h io.h data.h
